version: "3.7"
services:
    devkitarm:
        container_name: devkitarm
        build:
            context: ./
        logging:
            driver: "json-file"
        ports:
            - "3002:22"
        volumes:
            - devkitprovolume:/opt/devkitpro

volumes:
    devkitprovolume:
        name: devkitprovolume
        driver: local
        driver_opts:
            type: none
            device: YOUR_VOLUME_PATH_HERE
            o: bind
